timestamp:
seed: 42
model_repo_id: RecDol/PL_Multilabel_airflow
data_repo_id: RecDol/PLAYLIST_airflow

defaults:
  - _self_
  - path: default.yaml
  - data: default.yaml
  - model: default.yaml
  - trainer: default.yaml
  - wandb: default.yaml
